# Generated by Django 4.2.4 on 2023-09-11 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ProductImage',
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'ProductImage', 'verbose_name_plural': 'ProductImages'},
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='ProductImage',
        ),
    ]
