# Generated by Django 4.2.4 on 2023-09-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_image_productimage_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
