# Generated by Django 4.2.4 on 2023-09-01 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_items_orderitem_order_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
    ]
