# Generated by Django 4.2.4 on 2023-09-09 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_alter_orderitem_order_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_item',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.product'),
        ),
    ]
