# Generated by Django 4.2.4 on 2023-09-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Shipping', 'Shipping'), ('Delivered', 'Delivered'), ('Pending', 'Pending')], default='Pending', max_length=150, null=True),
        ),
    ]
